import {
  Moon,
  Sun,
  Search,
  Download,
  ShieldCheck,
  ShoppingCart,
  PlusCircle,
  CheckCircle2,
  X,
  Loader2,
  AlertTriangle,
  FileDown,
  Package,
  Github,
  type LucideProps,
} from "lucide-react"

export const Icons = {
  sun: Sun,
  moon: Moon,
  search: Search,
  download: Download,
  shieldCheck: ShieldCheck,
  shoppingCart: ShoppingCart,
  plusCircle: PlusCircle,
  checkCircle2: CheckCircle2,
  close: X,
  spinner: Loader2,
  warning: AlertTriangle,
  fileDown: FileDown,
  package: Package,
  github: Github,
}
